---
title: "Working Through the Left Ventricle Image Segmentation (Fourier) tutorial"
author: "Paul Pearson"
date: "January 14, 2016"
output: html_document
---

# Software to install

- [Jupyter and Anaconda Python](http://jupyter.readthedocs.org/en/latest/install.html#new-to-python-and-jupyter)

- The tutorial I used to get OpenCV to work on Windows 7 is [OpenCV (Open Computer Vision) installation on Windows for use as a Python package](http://mathalope.co.uk/2015/05/07/opencv-python-how-to-install-opencv-python-package-to-anaconda-windows/).  I do not think it is necessary for you to install the FFMPEG (video codec), since we are processing images (not videos).  There are [other ways to install OpenCV given on StackOverflow](http://stackoverflow.com/questions/23119413/how-to-install-python-opencv-through-conda)

- [Mango desktop dicom file viewer for Windows](http://ric.uthscsa.edu/mango/mango.html)


# Working through the Left Ventricle Segmentation Tutorial

- Link to the Left Ventricle Segmentation Tutorial as a [GitHub Gist](https://gist.github.com/ajsander/fb2350535c737443c4e0#file-tutorial-md) or the [post on the Kaggle website](https://www.kaggle.com/c/second-annual-data-science-bowl/details/fourier-based-tutorial)

- Link to the article by [Lin, et al. (2006)](https://www.researchgate.net/publication/6452142_Automated_Detection_of_Left_Ventricle_in_4D_MR_Images_Experience_from_a_Large_Study)

## Abbreviations and terms

- LV = Left Ventricle

- Image segmentation: "The goal of image segmentation is to divide an image into a set of semantically meaningful, homogeneous, and nonoverlapping regions of similar attributes such as intensity, depth, color, or texture. The segmentation result is either an image of labels identifying each homogeneous region or a set of contours which describe the region boundaries." [MRI Segmentation of the Human Brain: Challenges, Methods, and Applications](http://www.hindawi.com/journals/cmmm/2015/450341/)

- ROI = circular Region Of Interest

- Short axis stack: The [University of Minnesota Atlas of Cardiac Anatomy](http://www.vhlab.umn.edu/atlas/cardiac-mri/index.shtml) has a [brief description of the short axis stack along with a drop down menu allowing you to choose different hearts to view](http://www.vhlab.umn.edu/atlas/cardiac-mri/short-axis-stack/index.shtml).  They say "A short axis stack shows the complete series of images taken during an MRI stack sequence scan. These images are taken at 1-4mm intervals in a plane perpendicular to the long axis of the left ventricle."

# FAQ

- [The FAQ on the Kaggle forum](https://www.kaggle.com/c/second-annual-data-science-bowl/forums/t/17885/frequently-asked-questions)

# Videos

- The video [2nd Annual Data Science Bowl: Q&A with Dr. Michael Hansen and Dr. Andrew Arai, NIH/NHLBI](https://www.youtube.com/watch?v=wXUt_vjrF0c&feature=youtu.be) is in response to this [forum question](https://www.kaggle.com/c/second-annual-data-science-bowl/forums/t/18346/answers-q-a-with-principle-investigators-michael-hansen-ph-d-and-dr-andrew)


